newspaper_agency/urls.py
from django.urls import path

from newspaper_agency.views import (
    index,
    TopicListView,
    TopicCreatedView,
    TopicUpdateView,
    TopicDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreatedView,
    RedactorYearOfExperienceUpdateView,
    RedactorDeleteUpdateView,
    NewspapersListView,
    NewspapersDetailView,
    NewspapersCreateView,
    NewspapersUpdateView,
    NewspapersDeleteView,
    ToggleAssignToNewspaper
)

urlpatterns = [
    path(
        "",
        index,
        name="index"
    ),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list"
    ),
    path(
        "topics/create/",
        TopicCreatedView.as_view(),
        name="topic-create"
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update"
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete"
    ),
    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list"
    ),
    path(
        "redactors/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail"
    ),
    path(
        "redactors/create/",
        RedactorCreatedView.as_view(),
        name="redactor-create"
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorYearOfExperienceUpdateView.as_view(),
        name="redactor-update"
    ),
    path(
        "redactors/<int:pk>/delete/",
        RedactorDeleteUpdateView.as_view(),
        name="redactor-delete"
    ),
    path(
        "newspapers/",
        NewspapersListView.as_view(),
        name="newspaper-list"
    ),
    path(
        "newspapers/<int:pk>/detail/",
        NewspapersDetailView.as_view(),
        name="newspaper-detail"
    ),
    path(
        "newspapers/create/",
        NewspapersCreateView.as_view(),
        name="newspaper-create"
    ),
    path(
        "newspapers/<int:pk>/update/",
        NewspapersUpdateView.as_view(),
        name="newspaper-update"
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspapersDeleteView.as_view(),
        name="newspaper-delete"
    ),
    path(
        "newspapers/<int:pk>/toggle-assign/",
        ToggleAssignToNewspaper.as_view(),
        name="toggle-assign-to-newspaper"
    )
]

app_name = "newspaper_agency"

newspapers_agency_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper_agency.urls", namespace="newspaper_agency")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

newspaper_agency/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(default=0)

    class Meta:
        ordering = ["username"]

    def get_absolute_url(self):
        return reverse(
            "newspaper_agency:redactor-detail", kwargs={"pk": self.pk}
        )

    def __str__(self) -> str:
        return f"{self.username} ({self.first_name} {self.last_name})"


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    context = models.TextField()
    published_date = models.DateTimeField(auto_now=True)
    topic = models.ForeignKey(
        Topic,
        on_delete=models.CASCADE,
        related_name="newspapers"
    )
    publishers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="newspapers"
    )

    class Meta:
        ordering = ["title"]

    def get_absolute_url(self):
        return reverse("newspaper_agency:newspaper-list")

    def __str__(self) -> str:
        return f"{self.title} {self.context} {self.topic}"

newspaper_agency/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from newspaper_agency.models import Redactor, Newspaper, Topic


def validate_years_of_experience(years_of_experience):
    if not isinstance(years_of_experience, int):
        raise ValidationError(
            "Work experience should be integer number"
        )
    elif not (0 <= years_of_experience <= 100):
        raise ValidationError(
            "Work experience should be in the "
            f"range from 0 to 100, not {years_of_experience}"
        )
    return years_of_experience


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"})
    )


class RedactorSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by username"}
        )
    )


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )

    years_of_experience = forms.IntegerField(
        label="Years of Experience",
        required=True,
        widget=forms.TextInput(attrs={'id': 'years_of_experience'}),
        validators=[validate_years_of_experience],
    )


class RedactorYearOfExperienceUpdateForm(forms.ModelForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = ["years_of_experience"]

    years_of_experience = forms.IntegerField(
        label="Years of Experience",
        required=True,
        widget=forms.TextInput(attrs={'id': 'years_of_experience'}),
        validators=[validate_years_of_experience],
    )


class NewspapersSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by title"}
        )
    )


class NewspaperForm(forms.ModelForm):
    topic = forms.ModelChoiceField(
        queryset=Topic.objects.all(),
        label="Topic",
        required=True,
        widget=forms.Select(
            attrs={
                "id": "topic",
                "style": "background-color: rgba(255, 255, 255, 0.1);"
            }
        ),
    )
    context = forms.CharField(
        label="Context",
        widget=forms.Textarea(
            attrs={
                "id": "context",
                "style": "background-color: rgba(255, 255, 255, 0.1);"
            }

        ),
    )

    publishers = forms.ModelMultipleChoiceField(
        required=False,
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Newspaper
        fields = "__all__"

newspaper_agency/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic, View

from newspaper_agency.forms import (
    TopicSearchForm,
    RedactorSearchForm,
    RedactorCreationForm,
    RedactorYearOfExperienceUpdateForm,
    NewspapersSearchForm,
    NewspaperForm
)

from newspaper_agency.models import Topic, Newspaper, Redactor


def index(request):
    topics = Topic.objects.count()
    newspapers = Newspaper.objects.count()
    redactors = Redactor.objects.count()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_topics": topics,
        "num_newspapers": newspapers,
        "num_redactors": redactors,
        "num_visits": num_visits + 1,
    }

    return render(request, "newspaper_agency/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    context_object_name = "topic_list"
    template_name = "newspaper_agency/topic_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["topic_search"] = TopicSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Topic.objects.all()
        form = TopicSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class TopicCreatedView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper_agency:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper_agency:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("newspaper_agency:topic-list")


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    context_object_name = "redactor_list"
    template_name = "newspaper_agency/redactor_list.html"
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["redactor_search_form"] = RedactorSearchForm(
            initial={"username": username}
        )

        return context

    def get_queryset(self):
        queryset = get_user_model().objects.all()
        form = RedactorSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor
    template_name = "newspaper_agency/redactor_detail.html"


class RedactorCreatedView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm


class RedactorYearOfExperienceUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorYearOfExperienceUpdateForm
    template_name = "newspaper_agency/redactor_form.html"

    def get_success_url(self):
        return reverse_lazy(
            "newspaper_agency:redactor-detail", kwargs={"pk": self.object.id}
        )


class RedactorDeleteUpdateView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("newspaper_agency:redactor-list")


class NewspapersListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    template_name = "newspaper_agency/newspaper_list.html"
    context_object_name = "newspaper_list"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspapersListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        context["newspapers_search_form"] = NewspapersSearchForm(
            initial={"title": title}
        )

        return context

    def get_queryset(self):
        queryset = Newspaper.objects.select_related("topic")
        form = NewspapersSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                title__icontains=form.cleaned_data["title"]
            )


class NewspapersDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper
    template_name = "newspaper_agency/newspapers_detail.html"


class NewspapersCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    template_name = "newspaper_agency/newspaper_form.html"


class NewspapersUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm

    def get_success_url(self):
        return reverse_lazy(
            "newspaper_agency:newspaper-detail",
            kwargs={"pk": self.object.id}
        )


class NewspapersDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("newspaper_agency:newspaper-list")


class ToggleAssignToNewspaper(LoginRequiredMixin, View):
    def post(self, request, pk):
        redactor = Redactor.objects.get(id=request.user.id)
        newspaper = Newspaper.objects.get(id=pk)

        if newspaper in redactor.newspapers.all():
            redactor.newspapers.remove(newspaper)
        else:
            redactor.newspapers.add(newspaper)

        return HttpResponseRedirect(
            reverse_lazy("newspaper_agency:newspaper-detail", args=[pk])
        )

templates/newspaper_agency/newspaper_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<style>
      body {
          background-image: url(/static/img/redactors_newspapers.jpg);
          background-size: cover;
          padding-top: 150px;
          margin: 0;
      }

</style>
<div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-6 col-md-7 d-flex justify-content-center flex-column">
        <h1 style="color: #fff">Delete Newspaper?</h1>
        <h3 style="color: #fff">Are you sure you want to delete?</h3>
        <p class="lead pe-5 me-5" style="color: #fff">If you delete this newspaper, you will not be able to get it
          back, so think
          carefully if it is really necessary.</p>
        <div class="buttons">
          <form action="" method="post">
            {% csrf_token %}
            <button type="submit" class="btn bg-gradient-danger w-auto me-1 mb-0">Delete</button>
            <button type="button" class="btn bg-gradient-light w-auto me-1 mb-0" style="margin-left: 20px;">
              <a href="{% url 'newspaper_agency:newspaper-detail' pk=newspaper.id %}"
                 class="text-black-50"
              >
                No i don't want to delete
              </a>
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/newspaper_agency/newspaper_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<style>
      body {
          background-image: url(/static/img/create_update.jpg);
          background-size: cover;
          padding-top: 80px;
          margin: 0;
      }

      #contact-form label {
          color: #fff;
      }

      #contact-form input[type="text"],
      #contact-form input[type="color"],
      #contact-form textarea {
          background-color: rgba(255, 255, 255, 0.1);
          color: #fff;
      }
</style>
<section>
  <div class="container py-4">
    <div class="row">
      <div class="col-lg-7 mx-auto d-flex justify-content-center flex-column">
        <h3 class="text-center" style="color: #fff">{{ object|yesno:"Update,Create" }} newspaper</h3>
        <form action="" id="contact-form" method="post" novalidate>
          <div class="card-body">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="col-md-12">
              <button type="submit" class="btn bg-gradient-dark w-100">
                {{ object|yesno:"Update,Create" }}
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/newspaper_agency/newspaper_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<style>
      body {
          background-image: url(/static/img/redactors_newspapers.jpg);
          padding-top: 150px;
          margin: 0;
      }

      #contact-form input {
          color: #000;
      }



</style>

<div class="container">
  <div class="row py-4">
    <div class="col-lg-6">
      <h1 style="color: #fff">Newspaper List</h1>
      <h4 style="color: #fff">
        <strong>
          Here you can see brief information about all the newspapers on our website. You can create new ones and
          search for the ones that interest you.
        </strong>
      </h4>
      <br>
      <a
          href="{% url 'newspaper_agency:newspaper-create' %}"
          style=" color: #fff"
      >
        Click here to create
        <i class="fas fa-arrow-right text-sm ms-1"></i>
      </a>
    </div>
    <div class="col-lg-6 mt-lg-0 mt-5 ps-lg-0 ps-0">
      <div class="p-3 info-horizontal">
        <form action="" method="get" class="form-inline" id="contact-form">
          {% csrf_token %}
          {{ newspapers_search_form|crispy }}
        </form>
        <br>

        {% for newspaper in newspaper_list %}
        <div class="description">
          <h5 class="mb-0">
            <a
                href="{% url 'newspaper_agency:newspaper-detail' pk=newspaper.id %}"
                style="color: #fff  "
            >
              <strong>{{ newspaper.title }}</strong>
            </a>
          </h5>
          <h6 class="mb-0" style="color: #fff">Published date: [{{ newspaper.published_date }}]</h6>
          <br>
        </div>
        {% empty %}
        <h3 style="color: #fff">No newspapers!</h3>
        {% endfor %}

        <div style="margin-top: 30px;">
          {% include "includes/pagination.html" %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/newspaper_agency/newspapers_detail.html
{% extends "base.html" %}

{% block content %}
<style>
      body {
          background-image: url(/static/img/redactors_newspapers.jpg);
          background-size: cover;
          padding-top: 150px;
          margin: 0;
      }






</style>

<div class="container">

  <div style="float: right">

    <button
        type="button"
        class="btn bg-gradient-light w-auto me-1 mb-0"
    >
      <a href="{% url 'newspaper_agency:newspaper-update' pk=newspaper.id %}"
         class="text-black-50"
      >Update</a>
    </button>

    <button
        type="button"
        class="btn bg-gradient-light w-auto me-1 mb-0"
    >
      <a href="{% url 'newspaper_agency:newspaper-delete' pk=newspaper.id %}"
         class="text-black-50"
      >
        Delete
      </a>
    </button>
  </div>

  <div class="row py-4" style="color: #fff">
    <div class="col-lg-10">
      <h1 class="mt-2" style="color: #fff">{{ newspaper.title }}</h1>
      <br>
      <h3 style="color: #fff">{{ newspaper.context }}</h3>
      <br>
      <h5 style="color: #fff">Was published at {{ newspaper.published_date }}</h5>
      <h5 style="color: #fff">Topic: {{ newspaper.topic.name }}</h5>
    </div>

    <ul>
      <div class="col-lg-6 mt-lg-0 mt-5 ps-lg-0 ps-0">
        <h5 style="color: #fff">
          Redactors
          {% if newspaper not in user.newspapers.all %}
          <form method="post" action="{% url 'newspaper_agency:toggle-assign-to-newspaper' pk=newspaper.pk %}">
            {% csrf_token %}
            <button type="submit" class="btn bg-gradient-light w-auto me-1 mb-0" style="float: right">
              Assign me to this newspaper
            </button>
          </form>
          {% else %}
          <form method="post" action="{% url 'newspaper_agency:toggle-assign-to-newspaper' pk=newspaper.id %}">
            {% csrf_token %}
            <button type="submit" class="btn bg-gradient-light w-auto me-1 mb-0" style="float: right">
              Delete me from this newspaper
            </button>
          </form>
          {% endif %}
        </h5>
        {% for publisher in newspaper.publishers.all %}
        <div class="p-1 info-horizontal">
          <div class="description ps-3">
            <p class="mb-0">
              <a href="{% url 'newspaper_agency:redactor-detail' pk=publisher.id %}" style="color: #fff">
                <strong>{{ publisher.username }}</strong></a>
              <strong>{{ publisher.first_name }} {{ publisher.last_name }}</strong>
            </p>
          </div>
        </div>
      </div>


      {% empty %}
      <p>No Redactors</p>
      {% endfor %}
    </ul>

  </div>
</div>

{% endblock %}

templates/newspaper_agency/redactor_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<style>
      body {
          background-image: url(/static/img/redactors_newspapers.jpg);
          background-size: cover;
          padding-top: 150px;
          margin: 0;
      }

</style>

<div>
  <div class="page-header min-vh-50">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-6 col-md-7 d-flex justify-content-center flex-column">
          <h1 style="color: #fff">Delete Redactor?</h1>
          <h3 class="mb-4" style="color: #fff">Are you sure you want to delete?</h3>
          <p class="lead pe-5 me-5" style="color: #fff">If you delete this newspaper, you will not be able to get it
            back, so think
            carefully if it is really necessary.</p>
          <div class="buttons">
            <form action="" method="post">
              {% csrf_token %}

              <button type="submit" class="btn bg-gradient-danger w-auto me-1 mb-0">Delete</button>
              <button type="button" class="btn bg-gradient-light w-auto me-1 mb-0" style="margin-left: 20px;">
                <a href="{% url 'newspaper_agency:redactor-detail' pk=redactor.id %}">No i don't want to delete</a>
              </button>
            </form>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/newspaper_agency/redactor_detail.html
{% extends "base.html" %}

{% block content %}
<style>
      body {
          background-image: url(/static/img/redactors_newspapers.jpg);
          background-size: cover;
          padding-top: 150px;
          margin: 0;
      }

</style>
<div class="container">

  <div>
    <button
        type="button"
        class="btn bg-gradient-light w-auto me-1 mb-0"
    >
      <a href="{% url 'newspaper_agency:redactor-update' pk=redactor.id %}"
      >Update</a>
    </button>

    <button
        type="button"
        class="btn bg-gradient-light w-auto me-1 mb-0"
    >
      <a href="{% url 'newspaper_agency:redactor-delete' pk=redactor.id %}"
      >Delete</a>
    </button>
  </div>

  <div>
    <div class="page-header min-vh-50">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-6 col-md-7 d-flex justify-content-center flex-column">
            <h1 style="color: #fff">{{ redactor.username }}</h1>
            <h3 class="mb-4" style="color: #fff">{{ redactor.first_name }} {{ redactor.last_name }}</h3>
            <h4 class="mb-4" style="color: #fff">
              Years of experience: {{ redactor.years_of_experience }}<br>
              Is staff: {{ redactor.is_staff }}<br>
              Number of published newspapers {{ redactor.newspapers.count }}
            </h4>
            <div class="buttons">

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

{% endblock %}

templates/newspaper_agency/redactor_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<style>
      body {
          background-image: url(/static/img/create_update.jpg);
          background-size: cover;
          padding-top: 80px;
          margin: 0;
      }

      #contact-form label {
          color: #fff;
      }

      #contact-form input[type="text"],
      #contact-form input[type="password"],
      #contact-form textarea {
          background-color: rgba(255, 255, 255, 0.1);
          color: #fff;
      }


</style>
<section>
  <div class="container py-4">
    <div class="row">
      <div class="col-lg-7 mx-auto d-flex justify-content-center flex-column">
        <h3 class="text-center" style="color: #fff">{{ object|yesno:"Update,Create" }} redactor</h3>
        <form action="" id="contact-form" method="post" novalidate>
          <div class="card-body">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="col-md-12">
              <button type="submit" class="btn bg-gradient-dark w-100">
                {{ object|yesno:"Update,Create" }}
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/newspaper_agency/redactor_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<style>
      body {
          background-image: url(/static/img/redactors_newspapers.jpg);
          background-size: cover;
          padding-top: 150px;
          margin: 0;
      }

      #contact-form input {
          color: #000;
      }
</style>
<div class="container">
  <div class="row py-4">
    <div class="col-lg-6">
      <h1 style="color: #fff">Redactor List</h1>
      <h4 style="color: #fff">Here you can view brief information about the redactors that are on our site. You can
        create new ones and
        search for them by username.</h4>
      <a href="{% url 'newspaper_agency:redactor-create' %}" style="color: #fff">
        Click here to create
        <i class="fas fa-arrow-right text-sm ms-1"></i>
      </a>
    </div>

    {% block inner %}
    <div class="col-lg-6 mt-lg-0 mt-5 ps-lg-0 ps-0">
      <div class="p-3 info-horizontal">
        <form action="" method="get" class="form-inline" id="contact-form">
          {% csrf_token %}
          {{ redactor_search_form|crispy }}
        </form>
        <br>

        {% for redactor in redactor_list %}
        <div class="description">
          <h3>
            <a href="{% url 'newspaper_agency:redactor-detail' pk=redactor.id %}" style="color: #fff">
              Username: {{ redactor.username }}
            </a>
          </h3>
          <h4 style="color: #fff">Full name: {{ redactor.first_name }} {{ redactor.last_name }}</h4>

          <h4 class="mb-0" style="color: #fff">Years of
            experience: {{ redactor.years_of_experience }}</h4>
          <br>
        </div>
        {% empty %}
        <h3 style="color: #fff">No Redactors!</h3>
        {% endfor %}

        <div style="margin-top: 30px;">
          {% block pagination %}
          {% include "includes/pagination.html" %}
          {% endblock %}
        </div>
      </div>
    </div>
    {% endblock %}
  </div>
</div>
{% endblock %}

templates/newspaper_agency/topic_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<style>
      body {
          background-image: url(/static/img/topics/topic.png);
          padding-top: 150px;
          margin: 0;
      }

      #contact-form input {
          color: #000;
      }

</style>

<div class="container">
  <div class="row py-4">
    <div class="col-lg-6">
      <h1 style="color: #fff">
        Topic List
      </h1>
      <h4 style="color: #fff">
        Here you can see brief information about all the topics that are on our website. You can create new ones
        and search for the ones that interest you.
      </h4>
      <br>
      <a href="{% url 'newspaper_agency:topic-create' %}" style="color: #fff"
      >
        Click here to create
        <i class="fas fa-arrow-right text-sm ms-1"></i>
      </a>
    </div>

    {% block inner %}
    <div class="col-lg-6 mt-lg-0 mt-5 ps-lg-0 ps-0">
      <div class="p-3 info-horizontal">
        <form action="" method="get" class="form-inline" id="contact-form">
          {% csrf_token %}
          {{ topic_search|crispy }}
        </form>
        <br>

        {% for topic in topic_list %}
        <div class="description">
          <div class="mb-0 topics" style="display: flex; align-items: center; justify-content: space-between">
            <h5 style="color: #fff">{{ topic.name }}</h5>
            <div style="float: right">
              <button
                  type="button"
                  class="btn bg-gradient-light w-auto me-1 mb-0"
              >
                <a href="{% url 'newspaper_agency:topic-update' pk=topic.id %}"
                >Update
                </a>
              </button>

              <button
                  type="button"
                  class="btn bg-gradient-light w-auto me-1 mb-0"
              >
                <a href="{% url 'newspaper_agency:topic-delete' pk=topic.id %}"
                >Delete
                </a>
              </button>
            </div>
          </div>
          <br>
        </div>
        {% empty %}
        <h3 style="color: #fff">No Topics!</h3>
        {% endfor %}

        <div style="margin-top: 30px;">
          {% block pagination %}
          {% include "includes/pagination.html" %}
          {% endblock %}
        </div>
      </div>
    </div>
    {% endblock %}
  </div>
</div>
{% endblock %}